In [6]:
# Installation
# !pip install numpy

In [7]:
import numpy as np

In [8]:
np.__version__

'2.4.6'

### Creating Numpy Array

In [9]:
list1 = [1,2,3,4,5,6,7,8,9]

arry1 = np.array(list1)

In [12]:
arry1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arry1.shape

(9,)

In [14]:
arry1.ndim

1

In [16]:
list2 = [
    [1,2,3] , 
    [4,5,6] , 
    [7,8,9]
]
arry2 = np.array(list2)

In [17]:
arry2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arry2.shape

(3, 3)

In [19]:
arry2.ndim

2

In [22]:
list3 = [
    [
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ],[
        [1,2,3] , 
        [4,5,6] , 
        [7,8,9]
    ]
]
arry3 = np.array(list3)

In [23]:
arry3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
arry3.shape

(2, 3, 3)

In [26]:
arry3.ndim

3

NumPy arrays can be created in several ways. Here are some of the most common methods:

- `array()`: Creates NumPy arrays from Python lists
- `zeros()`: Creates NumPy arrays with all elements initialized to 0
- `ones()`: Creates NumPy arrays with all elements initialized to 1
- `full()`: Creates an array with all elements initialized to same user-specified value
- `arange()`: Creates NumPy arrays with a sequence of values (similar to python range() function)
- `linspace()`: Creates NumPy arrays with a sequence of evenly spaced values
- `diag()`: Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
- `eye()`: Creates NumPy array with ones on the diagonal and zeros elsewhere
- `identity()`: Creates an identity matrix
- `random.rand()`: Creates NumPy array of random numbers sampled from a uniform distribution

In [30]:
np.zeros(shape = (2, 3,6), dtype= "int")

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [35]:
np.ones(shape = (3,6,6), dtype="int")

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [36]:
np.full(shape = (3,4), fill_value=6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [37]:
np.arange(1,90,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

In [47]:
np.linspace((0, 1, 2), (30,20, 60) , num = 5, axis=0)

array([[ 0.  ,  1.  ,  2.  ],
       [ 7.5 ,  5.75, 16.5 ],
       [15.  , 10.5 , 31.  ],
       [22.5 , 15.25, 45.5 ],
       [30.  , 20.  , 60.  ]])

In [48]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.random.randint(0, 50, size = (3, 2,4))

array([[[14, 34, 44, 16],
        [22, 45, 21, 21]],

       [[25,  3,  4,  1],
        [13, 14, 21, 43]],

       [[15, 26, 31, 40],
        [29, 32, 10, 25]]])