## NumPy Array Properties and Methods

NumPy arrays have several useful properties and methods that can be used to manipulate them.

- `shape`: Property that returns the dimensions of the array
- `ndim`: Property that returns number of array dimensions
- `dtype`: Property that returns data-type of the array’s elements
- `T`: Transpose of the array’s elements
- -------------------------------------------------------------------
- `reshape()`: Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions
- `ravel()`: Method that collapses all values into a single axis or dimension and returns view of original array
- `flatten()`: Method that collapses all values into a single axis or dimension and returns an independent copy of original array
- `sum()`: Method that returns the sum of all elements in an array
- `cumsum()`: Method that returns cumulative sum over given axis
- `prod()`: Method that compute product over given axis
- `max()`: Method that returns the maximum along a given axis
- `argmax()`: Method that returns indeces of the maximum values along a given axis
- `clip()`: Clip values beyond range to threshold values
- `np.concatenate()`: Method to concatenate two or more arrays
- `np.split()`: Method to split an array into multiple sub-arrays
- `np.vstack()`: Method to stack arrays vertically
- `np.hstack()`: Method to stack arrays horizontally

In [6]:
import numpy as np

a = np.random.randint(10,50, size = (5, 2, 3), dtype="int16")

In [7]:
a.shape

(5, 2, 3)

In [8]:
a.ndim

3

In [9]:
a.dtype

dtype('int16')

In [10]:
a.T

array([[[39, 47, 12, 42, 20],
        [25, 46, 20, 25, 47]],

       [[26, 35, 11, 12, 39],
        [36, 41, 34, 49, 35]],

       [[37, 39, 33, 21, 28],
        [44, 22, 45, 32, 32]]], dtype=int16)

In [11]:
a.size

30

---

In [13]:
a = np.random.randint(10,50, size = (5, 4), dtype="int16")
a

array([[21, 30, 14, 23],
       [13, 35, 21, 47],
       [33, 41, 38, 15],
       [43, 13, 41, 38],
       [23, 23, 42, 44]], dtype=int16)

In [18]:
b = a.reshape(2,5,2)
b

array([[[21, 30],
        [14, 23],
        [13, 35],
        [21, 47],
        [33, 41]],

       [[38, 15],
        [43, 13],
        [41, 38],
        [23, 23],
        [42, 44]]], dtype=int16)

In [21]:
a.reshape(4,-1)

array([[21, 30, 14, 23, 13],
       [35, 21, 47, 33, 41],
       [38, 15, 43, 13, 41],
       [38, 23, 23, 42, 44]], dtype=int16)

In [22]:
a.flatten() #a.ravel()

array([21, 30, 14, 23, 13, 35, 21, 47, 33, 41, 38, 15, 43, 13, 41, 38, 23,
       23, 42, 44], dtype=int16)

In [23]:
a

array([[21, 30, 14, 23],
       [13, 35, 21, 47],
       [33, 41, 38, 15],
       [43, 13, 41, 38],
       [23, 23, 42, 44]], dtype=int16)

In [24]:
a.sum()

np.int64(598)

In [25]:
a.sum(axis = 0)

array([133, 142, 156, 167])

In [26]:
a.sum(axis = 1)

array([ 88, 116, 127, 135, 132])

### 0 -> column wise -> vertical
### 1 -> row wise -> horizontal

In [28]:
a.trace() # diagonal sum

np.int64(132)

In [31]:
a.cumsum(axis = 1)

array([[ 21,  51,  65,  88],
       [ 13,  48,  69, 116],
       [ 33,  74, 112, 127],
       [ 43,  56,  97, 135],
       [ 23,  46,  88, 132]])

In [33]:
a.prod(dtype=float)

np.float64(5.981836286376674e+28)

In [34]:
a.prod(axis = 0)

array([ 8909901, 12871950, 19238184, 27111480])

In [36]:
a.cumprod(axis = 1)

array([[    21,    630,   8820, 202860],
       [    13,    455,   9555, 449085],
       [    33,   1353,  51414, 771210],
       [    43,    559,  22919, 870922],
       [    23,    529,  22218, 977592]])

In [37]:
a

array([[21, 30, 14, 23],
       [13, 35, 21, 47],
       [33, 41, 38, 15],
       [43, 13, 41, 38],
       [23, 23, 42, 44]], dtype=int16)

In [39]:
a.argmax(axis = 0)

array([3, 2, 4, 1])

In [40]:
a.argmin(axis = 1)

array([2, 0, 3, 1, 0])

In [41]:
a.clip(min= 20, max = 40)

array([[21, 30, 20, 23],
       [20, 35, 21, 40],
       [33, 40, 38, 20],
       [40, 20, 40, 38],
       [23, 23, 40, 40]], dtype=int16)

In [42]:
# Concat or Joining

In [57]:
arr1 = np.random.randint(1,100, size = (3,3))
arr2 = np.random.randint(1,100, size = (3,3))

In [58]:
arr1, arr2

(array([[54, 56, 75],
        [93, 80, 48],
        [56, 51, 38]]),
 array([[31, 77, 19],
        [13, 49,  1],
        [14, 92, 23]]))

In [59]:
np.concatenate([arr1, arr2], axis = 0) #vstack

array([[54, 56, 75],
       [93, 80, 48],
       [56, 51, 38],
       [31, 77, 19],
       [13, 49,  1],
       [14, 92, 23]])

In [56]:
np.concatenate([arr1, arr2], axis = 1) # hstack

array([[14, 57, 47, 61, 75, 61,  5],
       [37, 43, 32, 61, 49, 71, 18],
       [72,  7, 94,  1, 44, 31, 57]])

In [60]:
np.vstack((arr1, arr2))

array([[54, 56, 75],
       [93, 80, 48],
       [56, 51, 38],
       [31, 77, 19],
       [13, 49,  1],
       [14, 92, 23]])

In [61]:
np.hstack([arr1, arr2])

array([[54, 56, 75, 31, 77, 19],
       [93, 80, 48, 13, 49,  1],
       [56, 51, 38, 14, 92, 23]])