In [1]:
import numpy as np

## 1. Elementwise Operations

https://numpy.org/doc/2.5/reference/routines.math.html

In [15]:
a = np.array(
    [
        [4,6,8], 
        [1,2,4]
    ]
)
b = np.random.randint(1, 45, size = (2,3))
c = np.linspace((0,5), (60,100), num = 4, dtype=int)

In [55]:
a, b, c

(array([[4, 6, 8],
        [1, 2, 4]]),
 array([[10, 20, 16],
        [30, 16, 19]]),
 array([[  0,   5],
        [ 20,  36],
        [ 40,  68],
        [ 60, 100]]))

### Arithmetic Operations

In [20]:
# a + b
np.add(a,b)

array([[14, 26, 24],
       [31, 18, 23]])

In [21]:
# a -b 
np.subtract(a, b)

array([[ -6, -14,  -8],
       [-29, -14, -15]])

In [23]:
# a ** 2
np.pow(a, 2)

array([[16, 36, 64],
       [ 1,  4, 16]])

In [28]:
# a % b
quo, rem = np.divmod(b,a)
rem

array([[2, 2, 0],
       [0, 0, 3]])

### Trignometric

In [29]:
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [31]:
cot = np.reciprocal(np.tan(b))
cot

array([[ 1.54235105,  0.44699511,  3.3263232 ],
       [-0.15611995,  3.3263232 ,  6.59676425]])

### Rounding operations

In [32]:
np.around(cot, 2)

array([[ 1.54,  0.45,  3.33],
       [-0.16,  3.33,  6.6 ]])

In [33]:
np.floor(cot)

array([[ 1.,  0.,  3.],
       [-1.,  3.,  6.]])

In [34]:
np.ceil(cot)

array([[ 2.,  1.,  4.],
       [-0.,  4.,  7.]])

## 2. Matrix Operations

In [44]:
# Transpose

# b.T
bT = np.transpose(b)
bT

array([[10, 30],
       [20, 16],
       [16, 19]])

In [49]:
# Matrix Multiplication

# a @ bT
# np.dot(a, bT)
res = a.dot(bT)
res

array([[288, 368],
       [114, 138]])

In [51]:
# Trace [Diagnoal sum]
d_sum = np.trace(res)
print(d_sum)

426


In [53]:
# Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [63]:
# Determinat
b = np.random.randint(1, 5, size = (3,3))

det_b = np.linalg.det(b)
det_b

np.float64(-8.000000000000002)

In [64]:
# Inverse
inv_b = np.linalg.inv(b)
inv_b

array([[ 1.25 , -0.25 , -0.75 ],
       [-1.   ,  0.   ,  1.   ],
       [ 0.125,  0.375, -0.375]])

Solve Equation : `4x + 2y = 8` , `5x + 3y = 9`

In [83]:
A = np.array([[4,2] ,[5,3]])
B = np.array([8,9])

In [84]:
A_inv = np.linalg.inv(A)

In [85]:
X = np.dot(A_inv, B)

In [86]:
X

array([ 3., -2.])

In [91]:
# Array Broadcasting
A

array([[4, 2],
       [5, 3]])

In [92]:
B

array([8, 9])

In [94]:
A + B

array([[12, 11],
       [13, 12]])